name: CityCore
version: 1.0.0
main: com.citycore.CityCore
api-version: 1.21
description: Cooperative medieval city plugin
depend: [Vault, Citizens]
commands:
  city:
    description: Gestion de la ville
    usage: /city <create|claim|expand|deposit|info|map>
    aliases: [c]